//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGAdonet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int CountryID { get; set; }

        [Required (ErrorMessage ="Ülke adý boþ býrakýlamaz.")]
        [MaxLength(20,ErrorMessage ="Ülke adý 20 karakterden fazla olamaz.")]
        public string CountryName { get; set; }

        [Required(ErrorMessage = "Ülkedeki kayýtlý kiþi sayýsý boþ býrakýlamaz.")]
        public int CountryCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
    }
}
